apiVersion: {{ codeready_api_version }} 
kind: CheCluster
metadata:
  name: codeready-workspaces-cluster
  namespace: {{ namespace_codeready_operator }}
spec:
  auth:
    externalIdentityProvider: false
    initialOpenShiftOAuthUser: true
    openShiftoAuth: true
  database:
    externalDb: false
  metrics:
    enable: true
  server:
    cheFlavor: codeready
    cheLogLevel: INFO
    customCheProperties: 
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: '3' # number of workspaces each user can create
    selfSignedCert: false
    gitSelfSignedCert: false
    workspaceNamespaceDefault: <username>-codeready
  storage:
    preCreateSubPaths: true
    pvcClaimSize: 1Gi
    pvcStrategy: common
  