apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: noobaa-operator-group
  namespace: {{ namespace_noobaa_operator }}
spec:
  targetNamespaces:
  - {{ namespace_noobaa_operator }}
