---

namespace_amqstreams_operator: amqstreams-demo # project namespace for AMQ streams operator and application
amqstreams_operator_version_label: v1.6.2 # Red Hat version of the AMQ streams operator
amqstreams_supported_kafka_version: 2.6.0 # Supported Apache Kafka version
amqstreams_operator_channel: stable
amqstreams_log_message_format_version: 2.6
amqstreams_inter_broker_protocol_version: 2.6
