apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ codeready_operator_package_name }}
  namespace: {{ namespace_codeready_operator }}
spec:
  channel: {{ codeready_operator_channel }}
  installPlanApproval: {{ codeready_operator_approval_strategy }}
  name: {{ codeready_operator_package_name }}
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ codeready_operator_name }}.{{ codeready_operator_version_label }}
