kind: Secret
apiVersion: v1
metadata:
  name: credential-sso-keycloak
  namespace: {{ namespace_sso_operator }}
  labels:
    app: keycloak
    keycloak: sso-keycloak
data:
  ADMIN_PASSWORD: {{ sso_admin_passwd | string | b64encode  }}
  ADMIN_USERNAME: {{ sso_admin_userid | string | b64encode  }}
type: Opaque