apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ fuseonline_operator_package_name }}
  namespace: {{ namespace_fuseonline_operator }}
spec:
  channel: {{ fuseonline_operator_channel }}
  installPlanApproval: {{ fuseonline_operator_approval_strategy }}
  name: {{ fuseonline_operator_package_name }}
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ fuseonline_operator_name }}.{{ fuseonline_operator_version_label }}
