apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: fuse-online
  namespace: {{ namespace_fuseonline_operator }}
spec:
  channel: {{ fuseonline_operator_channel }}
  installPlanApproval: {{ fuseonline_operator_approval_strategy }}
  name: fuse-online
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: fuse-online-operator.{{ fuseonline_operator_version_label }}
