apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: fuse-online
  namespace: {{ namespace_fuseonline_operator }}
spec:
  channel: fuse-online-7.7.x
  installPlanApproval: Automatic
  name: fuse-online
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: fuse-online-operator.{{ fuseonline_operator_version_label }}
