apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: red-hat-camel-k
  namespace: {{ namespace_fuseonline_operator }}
spec:
  channel: techpreview
  installPlanApproval: Automatic
  name: red-hat-camel-k
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: red-hat-camel-k-operator.{{ camelk_operator_version_label }}
