apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ camelk_operator_package_name }}
  namespace: {{ namespace_fuseonline_operator }}
spec:
  channel: {{ camelk_operator_channel }}
  installPlanApproval: {{ camelk_operator_approval_strategy }}
  name: {{ camelk_operator_package_name }}
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ camelk_operator_name }}.{{ camelk_operator_version_label }}
