apiVersion: {{ threescale_api_version }}
kind: APIManager
metadata:
  name: apim-apimanager
spec:
  tenantName: {{ threescale_tenant_name }}
  wildcardDomain: {{ ocp_domain }}
  resourceRequirementsEnabled: {{ api_resource_requirements_enabled }}
  system:
    fileStorage: 
      simpleStorageService:
        configurationSecretRef: 
          name: {{ api_aws_auth }}
