---

- name: uninstall mysql deployment
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "mysql57"
    kind: Deployment
    namespace: "{{ namespace_mysql }}"

- name: uninstall mysql project
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ namespace_mysql }}"
    kind: Project
