---

- name: uninstall sso custom resource
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "sso-keycloak"
    kind: Keycloak
    namespace: "{{ namespace_sso_operator }}"

- name: uninstall sso operator subscription
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ sso_operator_package_name }}"
    kind: Subscription
    namespace: "{{ namespace_sso_operator }}"

- name: uninstall sso project
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ namespace_sso_operator }}"
    kind: Project
