apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    certified: 'false'
    olm.targetNamespaces: api-designer
    repository: 'https://github.com/Apicurio/apicurio-operators/tree/master/apicurito'
    support: Apicurito Project
    alm-examples: |-
      [{
        "apiVersion": "apicur.io/v1alpha1",
        "kind": "Apicurito",
        "metadata": {
          "name": "apicurito-service"
        },
        "spec": {
          "size": 3
        }
      }]
    capabilities: Seamless Upgrades
    olm.operatorNamespace: api-designer
    containerImage: registry.redhat.io/fuse7-tech-preview/fuse-apicurito-operator
    createdAt: '2020-01-28T16:12:00Z'
    categories: Integration & Delivery
    description: Manages the installation and upgrades of the API Designer.
    olm.operatorGroup: api-designer-4kpk6
  selfLink: >-
    /apis/operators.coreos.com/v1alpha1/namespaces/api-designer/clusterserviceversions/apicuritooperator.v7.6.0
  resourceVersion: '838626'
  name: apicuritooperator.v7.6.0
  uid: 32e6031c-0cc9-423c-8bbd-52f051ae2735
  creationTimestamp: '2020-06-01T14:30:06Z'
  generation: 1
  namespace: api-designer
  labels:
    olm.api.e5e0614b7a9f09b3: provided
spec:
  customresourcedefinitions:
    owned:
      - description: CRD for Apicurito
        displayName: Apicurito CRD
        kind: Apicurito
        name: apicuritos.apicur.io
        version: v1alpha1
  apiservicedefinitions: {}
  keywords:
    - api
    - apicurio
    - apicurito
  displayName: Red Hat Integration - API Designer
  provider:
    name: Red Hat
  maturity: alpha
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  version: 7.6.0
  icon:
    - base64data: >-
        PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
      mediatype: image/svg+xml
  links:
    - name: APIcurito
      url: 'https://github.com/Apicurio/apicurito'
    - name: Apicurito operator
      url: 'https://github.com/Apicurio/apicurio-operators/tree/master/apicurito'
  install:
    spec:
      deployments:
        - name: apicurito-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: apicurito
                name: apicurito-operator
            strategy: {}
            template:
              metadata:
                creationTimestamp: null
                labels:
                  app: apicurito
                  name: apicurito-operator
              spec:
                containers:
                  - env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: apicurito-operator
                    image: >-
                      registry.redhat.io/fuse7-tech-preview/fuse-apicurito-operator:1.5
                    imagePullPolicy: Always
                    name: apicurito-operator
                    resources: {}
                serviceAccountName: apicurito
      permissions:
        - rules:
            - apiGroups:
                - ''
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - apps
              resourceNames:
                - apicurito
              resources:
                - deployments/finalizers
              verbs:
                - update
            - apiGroups:
                - apicur.io
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - route.openshift.io
              resources:
                - routes
              verbs:
                - get
                - list
                - create
                - update
                - watch
          serviceAccountName: apicurito
    strategy: deployment
  maintainers:
    - email: janstey@redhat.com
      name: Jon Anstey
  description: >
    The API Designer is a small/minimal version of Apicurio, a standalone API
    design studio that can be used to create new or edit existing API designs
    (using the OpenAPI specification).

    This operator supports the installation and upgrade of apicurito. Apicurito
    components are:
      - apicurito-ui (apicurito application)
      - apicurito route (to access apicurito from outside openshift)

    ### How to install

    When the operator is installed (you have created a subscription and the
    operator is running in the selected namespace) create a new CR of Kind
    Apicurito (click the Create New button). The CR spec contains all defaults.


    At the moment, following fields are supported as part of the CR:
      - size: how many pods your the apicurito operand will have.
    ### How to upgrade

    Upgrades are handle by OLM
  selector:
    matchLabels:
      name: apicurito-operator
  labels:
    name: apicurito-operator
status:
  conditions:
    - lastTransitionTime: '2020-06-01T14:30:07Z'
      lastUpdateTime: '2020-06-01T14:30:07Z'
      message: requirements not yet checked
      phase: Pending
      reason: RequirementsUnknown
    - lastTransitionTime: '2020-06-01T14:30:07Z'
      lastUpdateTime: '2020-06-01T14:30:07Z'
      message: one or more requirements couldn't be found
      phase: Pending
      reason: RequirementsNotMet
    - lastTransitionTime: '2020-06-01T14:30:08Z'
      lastUpdateTime: '2020-06-01T14:30:08Z'
      message: 'all requirements found, attempting install'
      phase: InstallReady
      reason: AllRequirementsMet
    - lastTransitionTime: '2020-06-01T14:30:09Z'
      lastUpdateTime: '2020-06-01T14:30:09Z'
      message: waiting for install components to report healthy
      phase: Installing
      reason: InstallSucceeded
    - lastTransitionTime: '2020-06-01T14:30:09Z'
      lastUpdateTime: '2020-06-01T14:30:09Z'
      message: >
        installing: waiting for deployment apicurito-operator to become ready:
        Waiting for rollout to finish: 0 of 1 updated replicas are available...
      phase: Installing
      reason: InstallWaiting
    - lastTransitionTime: '2020-06-01T14:30:23Z'
      lastUpdateTime: '2020-06-01T14:30:23Z'
      message: install strategy completed with no errors
      phase: Succeeded
      reason: InstallSucceeded
  lastTransitionTime: '2020-06-01T14:30:23Z'
  lastUpdateTime: '2020-06-01T14:30:23Z'
  message: install strategy completed with no errors
  phase: Succeeded
  reason: InstallSucceeded
  requirementStatus:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      message: CRD is present and Established condition is true
      name: apicuritos.apicur.io
      status: Present
      uuid: 459e5ff6-9cc0-4a7e-80f1-fff4160d3c24
      version: v1beta1
    - dependents:
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["*"],"apiGroups":[""],"resources":["pods","services","endpoints","persistentvolumeclaims","events","configmaps","secrets"]}
          status: Satisfied
          version: v1beta1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["*"],"apiGroups":["apps"],"resources":["deployments","daemonsets","replicasets","statefulsets"]}
          status: Satisfied
          version: v1beta1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["get","create"],"apiGroups":["monitoring.coreos.com"],"resources":["servicemonitors"]}
          status: Satisfied
          version: v1beta1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["update"],"apiGroups":["apps"],"resources":["deployments/finalizers"],"resourceNames":["apicurito"]}
          status: Satisfied
          version: v1beta1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["*"],"apiGroups":["apicur.io"],"resources":["*"]}
          status: Satisfied
          version: v1beta1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["get","list","create","update","watch"],"apiGroups":["route.openshift.io"],"resources":["routes"]}
          status: Satisfied
          version: v1beta1
      group: ''
      kind: ServiceAccount
      message: ''
      name: apicurito
      status: Present
      version: v1