apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    olm.skipRange: '>=7.7.0 <7.7.1'
    certified: 'false'
    olm.targetNamespaces: apicurito-test
    operatorframework.io/properties: >-
      {"properties":[{"type":"olm.gvk","value":{"group":"apicur.io","kind":"Apicurito","version":"v1alpha1"}},{"type":"olm.package","value":{"packageName":"fuse-apicurito","version":"7.7.1"}}]}
    repository: 'https://github.com/Apicurio/apicurio-operators/tree/master/apicurito'
    support: Apicurito Project
    alm-examples: |-
      [{
              "apiVersion": "apicur.io/v1alpha1",
              "kind": "Apicurito",
              "metadata": {
                "name": "apicurito-service"
              },
              "spec": {
                "size": 2
              }
            }]
    capabilities: Seamless Upgrades
    olm.operatorNamespace: apicurito-test
    containerImage: 'registry.redhat.io/fuse7-tech-preview/fuse-apicurito-operator:1.7'
    createdAt: '2020-06-09 10:50:34'
    categories: Integration & Delivery
    description: >-
      Manages the installation and upgrades of the API Designer, a small/minimal
      version of Apicurio
    olm.operatorGroup: apicurito-test-q2bl7
  selfLink: >-
    /apis/operators.coreos.com/v1alpha1/namespaces/apicurito-test/clusterserviceversions/apicuritooperator.v7.7.1
  resourceVersion: '170059'
  name: apicuritooperator.v7.7.1
  uid: 1a261e44-04eb-4f4d-ac64-230dd4675c85
  creationTimestamp: '2020-11-23T18:27:39Z'
  generation: 1
  managedFields:
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:createdAt': {}
            'f:alm-examples': {}
            'f:description': {}
            'f:capabilities': {}
            'f:olm.skipRange': {}
            .: {}
            'f:containerImage': {}
            'f:categories': {}
            'f:certified': {}
            'f:operatorframework.io/properties': {}
            'f:support': {}
            'f:repository': {}
        'f:spec':
          'f:version': {}
          'f:maturity': {}
          'f:provider':
            .: {}
            'f:name': {}
          'f:links': {}
          'f:install':
            .: {}
            'f:spec':
              .: {}
              'f:clusterPermissions': {}
              'f:deployments': {}
              'f:permissions': {}
            'f:strategy': {}
          'f:maintainers': {}
          'f:description': {}
          'f:installModes': {}
          'f:icon': {}
          'f:customresourcedefinitions':
            .: {}
            'f:owned': {}
          .: {}
          'f:apiservicedefinitions': {}
          'f:selector':
            .: {}
            'f:matchLabels':
              .: {}
              'f:name': {}
          'f:labels':
            .: {}
            'f:name': {}
          'f:displayName': {}
          'f:keywords': {}
      manager: catalog
      operation: Update
      time: '2020-11-23T18:27:39Z'
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:olm.operatorGroup': {}
            'f:olm.operatorNamespace': {}
            'f:olm.targetNamespaces': {}
          'f:labels':
            .: {}
            'f:olm.api.e5e0614b7a9f09b3': {}
            'f:operators.coreos.com/fuse-apicurito.apicurito-test': {}
        'f:status':
          .: {}
          'f:conditions': {}
          'f:lastTransitionTime': {}
          'f:lastUpdateTime': {}
          'f:message': {}
          'f:phase': {}
          'f:reason': {}
          'f:requirementStatus': {}
      manager: olm
      operation: Update
      time: '2020-11-23T18:27:48Z'
  namespace: apicurito-test
  labels:
    olm.api.e5e0614b7a9f09b3: provided
    operators.coreos.com/fuse-apicurito.apicurito-test: ''
spec:
  customresourcedefinitions:
    owned:
      - description: CRD for Apicurito
        displayName: Apicurito CRD
        kind: Apicurito
        name: apicuritos.apicur.io
        specDescriptors:
          - description: The number of Apicurito pods to deploy
            displayName: Size
            path: size
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:Deployment'
              - 'urn:alm:descriptor:com.tectonic.ui:podCount'
          - description: The image used for the Apicurito deployment
            displayName: Image
            path: image
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:fieldGroup:Deployment'
              - 'urn:alm:descriptor:com.tectonic.ui:text'
        version: v1alpha1
  apiservicedefinitions: {}
  keywords:
    - api
    - apicurio
    - apicurito
  displayName: API Designer
  provider:
    name: Red Hat
  maturity: alpha
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  version: 7.7.1
  icon:
    - base64data: >-
        PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2Q3MWUwMDt9LmNscy0ye2ZpbGw6I2MyMWEwMDt9LmNscy0ze2ZpbGw6I2ZmZjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPnByb2R1Y3RpY29uc18xMDE3X1JHQl9BUEkgZmluYWwgY29sb3I8L3RpdGxlPjxnIGlkPSJMYXllcl8xIiBkYXRhLW5hbWU9IkxheWVyIDEiPjxjaXJjbGUgY2xhc3M9ImNscy0xIiBjeD0iNTAiIGN5PSI1MCIgcj0iNTAiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0yMC43MSA1MCkgcm90YXRlKC00NSkiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik04NS4zNiwxNC42NEE1MCw1MCwwLDAsMSwxNC42NCw4NS4zNloiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik01MC4yNSwzMC44M2EyLjY5LDIuNjksMCwxLDAtMi42OC0yLjY5QTIuNjUsMi42NSwwLDAsMCw1MC4yNSwzMC44M1pNNDMuMzYsMzkuNGEzLjM1LDMuMzUsMCwwLDAsMy4zMiwzLjM0LDMuMzQsMy4zNCwwLDAsMCwwLTYuNjdBMy4zNSwzLjM1LDAsMCwwLDQzLjM2LDM5LjRabTMuOTIsOS44OUEyLjY4LDIuNjgsMCwxLDAsNDQuNiw1MiwyLjcsMi43LDAsMCwwLDQ3LjI4LDQ5LjI5Wk0zMi42MywyOS42NWEzLjI2LDMuMjYsMCwxLDAtMy4yNC0zLjI2QTMuMjYsMy4yNiwwLDAsMCwzMi42MywyOS42NVpNNDAuNTMsMzRhMi43NywyLjc3LDAsMCwwLDAtNS41MywyLjc5LDIuNzksMCwwLDAtMi43NiwyLjc3QTIuODUsMi44NSwwLDAsMCw0MC41MywzNFptMS43Ni05LjMxYTQuNCw0LjQsMCwxLDAtNC4zOC00LjRBNC4zNyw0LjM3LDAsMCwwLDQyLjI5LDI0LjcxWk0zMi43OCw0OWE3LDcsMCwxLDAtNy03QTcsNywwLDAsMCwzMi43OCw0OVptMzIuMTMtNy43YTQuMjMsNC4yMywwLDAsMCw0LjMsNC4zMSw0LjMxLDQuMzEsMCwxLDAtNC4zLTQuMzFabTYuOSwxMC4wNmEzLjA4LDMuMDgsMCwxLDAsMy4wOC0zLjA5QTMuMDksMy4wOSwwLDAsMCw3MS44MSw1MS4zOFpNNzMuOSwzNC43N2E0LjMxLDQuMzEsMCwxLDAtNC4zLTQuMzFBNC4yOCw0LjI4LDAsMCwwLDczLjksMzQuNzdaTTUyLjE2LDQ1LjA2YTMuNjUsMy42NSwwLDEsMCwzLjY1LTMuNjZBMy42NCwzLjY0LDAsMCwwLDUyLjE2LDQ1LjA2Wk01NSwyMmEzLjE3LDMuMTcsMCwwLDAsMy4xNi0zLjE3QTMuMjMsMy4yMywwLDAsMCw1NSwxNS42MywzLjE3LDMuMTcsMCwwLDAsNTUsMjJabS0uNDcsMTAuMDlBNS4zNyw1LjM3LDAsMCwwLDYwLDM3LjU0YTUuNDgsNS40OCwwLDEsMC01LjQ1LTUuNDhaTTY2LjI1LDI1LjVhMi42OSwyLjY5LDAsMSwwLTIuNjgtMi42OUEyLjY1LDIuNjUsMCwwLDAsNjYuMjUsMjUuNVpNNDUuNyw2My4xYTMuNDIsMy40MiwwLDEsMC0zLjQxLTMuNDJBMy40MywzLjQzLDAsMCwwLDQ1LjcsNjMuMVptMTQsMTEuMTlhNC40LDQuNCwwLDEsMCw0LjM4LDQuNEE0LjM3LDQuMzcsMCwwLDAsNTkuNzMsNzQuMjlaTTYyLjMsNTAuNTFhOS4yLDkuMiwwLDEsMCw5LjE2LDkuMkE5LjIyLDkuMjIsMCwwLDAsNjIuMyw1MC41MVpNNTAuMSw2Ni43N2EyLjY5LDIuNjksMCwxLDAsMi42OCwyLjY5QTIuNywyLjcsMCwwLDAsNTAuMSw2Ni43N1pNODEuMjUsNDEuMTJhMi43LDIuNywwLDAsMC0yLjY4LDIuNjksMi42NSwyLjY1LDAsMCwwLDIuNjgsMi42OSwyLjY5LDIuNjksMCwwLDAsMC01LjM3Wk00NC40OSw3Ni40N2EzLjczLDMuNzMsMCwwLDAtMy43MywzLjc0LDMuNzcsMy43NywwLDEsMCwzLjczLTMuNzRaTTc5LjA2LDU2LjcyYTQsNCwwLDEsMCw0LDRBNCw0LDAsMCwwLDc5LjA2LDU2LjcyWm0tNiwxMS43OEEzLjA5LDMuMDksMCwwLDAsNzAsNzEuNmEzLDMsMCwwLDAsMy4wOCwzLjA5LDMuMDksMy4wOSwwLDAsMCwwLTYuMTlaTTI4LjMsNjhhNC4xNiw0LjE2LDAsMCwwLTQuMTQsNC4xNUE0LjIxLDQuMjEsMCwwLDAsMjguMyw3Ni4zYTQuMTUsNC4xNSwwLDAsMCwwLTguM1ptLTguMjItOWEzLDMsMCwxLDAsMywzQTMuMDUsMy4wNSwwLDAsMCwyMC4wOCw1OVptMS44NC05Ljc0YTMsMywwLDEsMCwzLDNBMy4wNSwzLjA1LDAsMCwwLDIxLjkxLDQ5LjIyWk0yMi4zNyw0MmEzLjI0LDMuMjQsMCwxLDAtMy4yNCwzLjI2QTMuMjYsMy4yNiwwLDAsMCwyMi4zNyw0MlpNNDMuMTEsNzAuMmEzLjgsMy44LDAsMCwwLTMuODEtMy43NCwzLjczLDMuNzMsMCwwLDAtMy43MywzLjc0QTMuOCwzLjgsMCwwLDAsMzkuMyw3NCwzLjg3LDMuODcsMCwwLDAsNDMuMTEsNzAuMlpNMzcuNTYsNTguNDNhNC42OCw0LjY4LDAsMCwwLTQuNjItNC42NCw0LjYzLDQuNjMsMCwwLDAtNC42Miw0LjY0LDQuNTgsNC41OCwwLDAsMCw0LjYyLDQuNjRBNC42Myw0LjYzLDAsMCwwLDM3LjU2LDU4LjQzWk0yMy4xMSwzMy44MmEyLjUyLDIuNTIsMCwxLDAtMi41MS0yLjUyQTIuNTMsMi41MywwLDAsMCwyMy4xMSwzMy44MloiLz48L2c+PC9zdmc+
      mediatype: image/svg+xml
  links:
    - name: Apicurito source code
      url: 'https://github.com/Apicurio/apicurito'
    - name: Apicurito operator source code
      url: 'https://github.com/Apicurio/apicurio-operators/tree/master/apicurito'
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - console.openshift.io
              resources:
                - consolelinks
                - consoleyamlsamples
              verbs:
                - get
                - create
                - list
                - update
                - delete
          serviceAccountName: apicurito
      deployments:
        - name: apicurito-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: apicurito
                name: apicurito-operator
            strategy: {}
            template:
              metadata:
                creationTimestamp: null
                labels:
                  app: apicurito
                  name: apicurito-operator
              spec:
                containers:
                  - env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: RELATED_IMAGE_APICURITO_OPERATOR
                        value: >-
                          registry.redhat.io/fuse7-tech-preview/fuse-apicurito-operator:1.7
                      - name: RELATED_IMAGE_APICURITO
                        value: 'registry.redhat.io/fuse7/fuse-apicurito:1.7'
                      - name: RELATED_IMAGE_GENERATOR
                        value: 'registry.redhat.io/fuse7/fuse-apicurito-generator:1.7'
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: apicurito-operator
                    image: >-
                      registry.redhat.io/fuse7-tech-preview/fuse-apicurito-operator:1.7
                    imagePullPolicy: Always
                    name: apicurito-operator
                    resources: {}
                serviceAccountName: apicurito
      permissions:
        - rules:
            - apiGroups:
                - ''
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                - serviceaccounts
              verbs:
                - '*'
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - apps
              resourceNames:
                - apicurito
              resources:
                - deployments/finalizers
              verbs:
                - update
            - apiGroups:
                - apicur.io
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - route.openshift.io
              resources:
                - routes
              verbs:
                - get
                - list
                - create
                - update
                - watch
          serviceAccountName: apicurito
    strategy: deployment
  maintainers:
    - email: apicurio@lists.jboss.org
      name: Apicurito Project
  description: >
    The API Designer is a small/minimal version of Apicurio, a standalone API
    design studio that can be used to create new or edit existing API designs
    (using the OpenAPI specification).


    This operator supports the installation and upgrade of apicurito. Apicurito
    components are:
       - apicurito-ui (apicurito application)
       - apicurito route (to access apicurito from outside openshift)

    ### How to install

    When the operator is installed (you have created a subscription and the
    operator is running in the selected namespace) create a new CR of Kind
    Apicurito (click the Create New button). The CR spec contains all defaults.


    At the moment, following fields are supported as part of the CR:
       - size: number of replicas
       - image: For testing purposes only. Changing this image in an existing installation will trigger an upgrade of the operand.
    ### How to upgrade

    Upgrades are triggered by updating the image field in the CR. This can be
    done manually via the Openshift console, or with kubectl:

    ```

    $ cat apicurito_cr.yaml
        apiVersion: apicur.io/v1alpha1
          kind: Apicurito
          metadata:
            name: apicurito-service
          spec:
            size: 3
     $ kubectl apply -f apicurito_cr.yaml
    ```
  selector:
    matchLabels:
      name: apicuritooperator
  labels:
    name: apicuritooperator
status:
  conditions:
    - lastTransitionTime: '2020-11-23T18:27:39Z'
      lastUpdateTime: '2020-11-23T18:27:39Z'
      message: requirements not yet checked
      phase: Pending
      reason: RequirementsUnknown
    - lastTransitionTime: '2020-11-23T18:27:39Z'
      lastUpdateTime: '2020-11-23T18:27:39Z'
      message: 'all requirements found, attempting install'
      phase: InstallReady
      reason: AllRequirementsMet
    - lastTransitionTime: '2020-11-23T18:27:39Z'
      lastUpdateTime: '2020-11-23T18:27:39Z'
      message: waiting for install components to report healthy
      phase: Installing
      reason: InstallSucceeded
    - lastTransitionTime: '2020-11-23T18:27:39Z'
      lastUpdateTime: '2020-11-23T18:27:40Z'
      message: >
        installing: waiting for deployment apicurito-operator to become ready:
        Waiting for deployment spec update to be observed...
      phase: Installing
      reason: InstallWaiting
    - lastTransitionTime: '2020-11-23T18:27:48Z'
      lastUpdateTime: '2020-11-23T18:27:48Z'
      message: install strategy completed with no errors
      phase: Succeeded
      reason: InstallSucceeded
  lastTransitionTime: '2020-11-23T18:27:48Z'
  lastUpdateTime: '2020-11-23T18:27:48Z'
  message: install strategy completed with no errors
  phase: Succeeded
  reason: InstallSucceeded
  requirementStatus:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      message: CRD is present and Established condition is true
      name: apicuritos.apicur.io
      status: Present
      uuid: e9ce5333-bb56-4613-899a-04cd8df1f8e2
      version: v1
    - dependents:
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["*"],"apiGroups":[""],"resources":["pods","services","endpoints","persistentvolumeclaims","events","configmaps","secrets","serviceaccounts"]}
          status: Satisfied
          version: v1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["*"],"apiGroups":["apps"],"resources":["deployments","daemonsets","replicasets","statefulsets"]}
          status: Satisfied
          version: v1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["get","create"],"apiGroups":["monitoring.coreos.com"],"resources":["servicemonitors"]}
          status: Satisfied
          version: v1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["update"],"apiGroups":["apps"],"resources":["deployments/finalizers"],"resourceNames":["apicurito"]}
          status: Satisfied
          version: v1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["*"],"apiGroups":["apicur.io"],"resources":["*"]}
          status: Satisfied
          version: v1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["get","list","create","update","watch"],"apiGroups":["route.openshift.io"],"resources":["routes"]}
          status: Satisfied
          version: v1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            cluster
            rule:{"verbs":["get","create","list","update","delete"],"apiGroups":["console.openshift.io"],"resources":["consolelinks","consoleyamlsamples"]}
          status: Satisfied
          version: v1
      group: ''
      kind: ServiceAccount
      message: ''
      name: apicurito
      status: Present
      version: v1
