apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ apicurito_operator_package_name }}
  namespace: {{ namespace_apicurito_operator }}
spec:
  channel: {{ apicurito_operator_channel }}
  installPlanApproval: {{ apicurito_operator_approval_strategy }}
  name: {{ apicurito_operator_package_name }}
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ apicurito_operator_name }}.{{ apicurito_operator_version_label }}
