apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: fuse-apicurito
  namespace: {{ namespace_apicurito_operator }}
spec:
  channel: {{ apicurito_operator_channel }}
  installPlanApproval: {{ apicurito_operator_approval_strategy }}
  name: fuse-apicurito
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: fuse-apicurito.{{ apicurito_operator_version_label }}
