apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: fuse-apicurito
  namespace: {{ namespace_apicurito_operator }}
spec:
  channel: fuse-apicurito-7.7.x
  installPlanApproval: Automatic
  name: fuse-apicurito
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: apicuritooperator.{{ apicurito_operator_version_label }}
