apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amqstreams-operator-group
  namespace: {{ namespace_amqstreams_operator }}
spec:
  targetNamespaces:
  - {{ namespace_amqstreams_operator }}
