kind: Secret
apiVersion: v1
metadata:
  name: system-smtp
  namespace: {{ namespace_threescale_operator }}
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: smtp
data:
  address: {{ smtp_host | string | b64encode  }}
  authentication: {{ smtp_authentication | string | b64encode  }}
  domain: ''
  openssl.verify.mode: ''
  password: {{ smtp_passwd | string | b64encode  }}
  port: {{ smtp_port | string | b64encode  }}
  username: {{ smtp_userid | string | b64encode  }}
type: Opaque
