kind: Secret
apiVersion: v1
metadata:
  name: system-seed
  namespace: {{ namespace_threescale_operator }}
  labels:
    app: 3scale-api-management
    threescale_component: system
data:
  ADMIN_ACCESS_TOKEN: {{ threescale_admin_access_token | string | b64encode }}
  ADMIN_EMAIL: ''
  ADMIN_PASSWORD: {{ threescale_admin_passwd | string | b64encode  }}
  ADMIN_USER: {{ threescale_admin_userid | string | b64encode  }}
  MASTER_ACCESS_TOKEN: {{ threescale_master_access_token | string | b64encode  }}
  MASTER_DOMAIN: {{ threescale_master_domain | string | b64encode  }}
  MASTER_PASSWORD: {{ threescale_master_passwd | string | b64encode  }}
  MASTER_USER: {{ threescale_master_userid | string | b64encode  }}
  TENANT_NAME: {{ threescale_tenant_name | string | b64encode  }}
type: Opaque