apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
  namespace: {{ namespace_sso_operator }}
spec:
  channel: {{ sso_operator_channel }}
  installPlanApproval: {{ sso_operator_approval_strategy }}
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhsso-operator.{{ sso_operator_version_label }}
