---

- name: uninstall apicurito 
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "apicurito-service"
    kind: Apicurito
    namespace: "{{ namespace_apicurito_operator }}"

- name: uninstall apicurito operator subscription
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ apicurito_operator_package_name }}"
    kind: Subscription
    namespace: "{{ namespace_apicurito_operator }}"

- name: uninstall apicurito project
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ namespace_apicurito_operator }}"
    kind: Project
