---

- name: uninstall fuseonline syndesis custom resource
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "syndesis-service"
    kind: Syndesis
    namespace: "{{ namespace_fuseonline_operator }}"

- name: uninstall camelk integration platform
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "camel-k"
    kind: IntegrationPlatform
    namespace: "{{ namespace_fuseonline_operator }}"

- name: uninstall fuseonline operator subscription
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ fuseonline_operator_package_name }}"
    kind: Subscription
    namespace: "{{ namespace_fuseonline_operator }}"

- name: uninstall camelk operator subscription
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ camelk_operator_package_name }}"
    kind: Subscription
    namespace: "{{ namespace_fuseonline_operator }}"

- name: uninstall fuseonline project
  oc_obj:
    state: absent
    oc_binary: "{{ openshift_cli }}"
    name: "{{ namespace_fuseonline_operator }}"
    kind: Project
