apiVersion: {{ amqstreams_api_version }}
kind: KafkaBridge
metadata:
  name: kafka-bridge
  namespace: {{ namespace_amqstreams_operator }}
spec:
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9092
  http:
    port: 8080