apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnectS2I
metadata:
  name: kafka-connect-s2i-cluster
  namespace: {{ namespace_amqstreams_operator }}
  annotations:
  # use-connector-resources configures this KafkaConnect
  # to use KafkaConnector resources to avoid
  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  version: {{ amqstreams_supported_kafka_version }}
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: kafka-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-s2i-cluster
    offset.storage.topic: connect-s2i-cluster-offsets
    config.storage.topic: connect-s2i-cluster-configs
    status.storage.topic: connect-s2i-cluster-status
