apiVersion: syndesis.io/v1beta1
kind: Syndesis
metadata:
  name: syndesis-service
  namespace: {{ namespace_fuseonline_operator }}
spec:
  components:
    server:
      features:
        managementUrlFor3scale: "https://{{ threescale_tenant_name }}-admin.{{ ocp_domain }}"
  addons:
    camelk:
      enabled: false
    dv:
      enabled: false
      resources:
        memory: 1024Mi
    jaeger:
      enabled: true
    knative:
      enabled: false
    todo:
      enabled: true
    ops:
      enabled: false
    publicApi:
      enabled: false
