apiVersion: {{ fuseonline_api_version }}
kind: Syndesis
metadata:
  name: syndesis-service
  namespace: {{ namespace_fuseonline_operator }}
  labels:
    app: syndesis
spec:
  components:
    server:
      features:
        managementUrlFor3scale: "https://{{ threescale_tenant_name }}-admin.{{ ocp_domain }}"
  addons:
    jaeger:
      enabled: true
    todo:
      enabled: false
    ops:
      enabled: false
    publicApi:
      enabled: true
