apiVersion: syndesis.io/v1beta2
kind: Syndesis
metadata:
  name: syndesis-service
  namespace: {{ namespace_fuseonline_operator }}
spec:
  components:
    server:
      features:
        managementUrlFor3scale: "https://{{ threescale_tenant_name }}-admin.{{ ocp_domain }}"
  addons:
    jaeger:
      enabled: true
    todo:
      enabled: false
    ops:
      enabled: false
    publicApi:
      enabled: false
